"use client";
import { useQuery } from "@tanstack/react-query";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { json, useAction, dateLabel, ErrorMessage, selectClass } from "./client";
type Window = { id: string; date: string; timeFrom: string; timeTo: string; available: boolean; note: string | null; userId: string; member: { user: { firstName: string; lastName: string } } };
import { useCurrentMember } from "@/lib/hooks/use-current-member";
export function Availability() {
  const { data: me } = useCurrentMember(), action = useAction();
  const query = useQuery({ queryKey: ["availability"], queryFn: () => json<{ availabilities: Window[] }>("/api/availability") });
  return <section className="space-y-4"><h2 className="text-[16px] font-semibold tracking-[-0.02em]">Verfügbarkeit</h2><p className="text-sm text-muted-foreground">Trage Zeitfenster ein. Bei Nachtzeiten liegt das Ende am Folgetag. Ohne Eintrag besteht keine Einschränkung.</p><Card className="p-4"><form className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5" onSubmit={async e => { e.preventDefault(); const f = e.currentTarget, d = new FormData(f); await action.mutateAsync({ url: "/api/availability", data: { date: d.get("date"), timeFrom: d.get("timeFrom"), timeTo: d.get("timeTo"), available: d.get("available") === "true", note: d.get("note") } }).then(() => f.reset()).catch(() => {}); }}><label>Datum<Input type="date" name="date" required /></label><label>Von<Input type="time" name="timeFrom" required /></label><label>Bis<Input type="time" name="timeTo" required /></label><label>Status<select className={selectClass} name="available"><option value="true">Verfügbar</option><option value="false">Nicht verfügbar</option></select></label><label>Hinweis<Input name="note" maxLength={500} /></label><Button disabled={action.isPending}>Zeitfenster speichern</Button></form></Card><ErrorMessage error={query.error} />{query.isPending ? <p>Lädt …</p> : <div className="space-y-2">{!query.data?.availabilities.length && <p className="text-sm text-muted-foreground">Für die kommenden 90 Tage sind keine Zeitfenster eingetragen.</p>}{query.data?.availabilities.map(w => <div className="flex flex-wrap items-center justify-between gap-3 akro-panel p-3" key={w.id}><div><p>{w.member.user.firstName} {w.member.user.lastName} · {dateLabel(w.date)} · {w.timeFrom}–{w.timeTo}</p><p className="text-sm text-muted-foreground">{w.available ? "Verfügbar" : "Nicht verfügbar"}{w.note ? " · " + w.note : ""}</p></div>{me?.user.id === w.userId && <Button variant="outline" size="sm" disabled={action.isPending} onClick={() => action.mutate({ url: "/api/availability", method: "DELETE", data: { id: w.id } })}>Entfernen</Button>}</div>)}</div>}</section>;
}
