"use client";
import { useQuery } from "@tanstack/react-query";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { json, useAction, ErrorMessage, dateLabel } from "./client";
// Namen, Notizen und Aktionen liefert der Server nur, soweit sie freigegeben sind.
type RequestRow = { id: string; kind: string; state: string; userId: string | null; targetUserId: string | null; note: string | null; user: { firstName: string; lastName: string } | null; shift: { date: string; title: string | null; shiftFrom: string; shiftTo: string; branch: { name: string; customer: { name: string } | null } | null }; can: { decide: boolean; volunteer: boolean; withdraw: boolean } };
type Correction = { id: string; status: string; reason: string; before: Record<string, unknown>; proposed: Record<string, unknown>; canDecide: boolean; record: { date: string; user: { firstName: string; lastName: string }; branch: { name: string } | null } };
const labels: Record<string,string> = { OPEN: "Offen", ACCEPTED: "Genehmigt", DECLINED: "Abgelehnt", PENDING: "Zur Freigabe", APPROVED: "Genehmigt" };
const fieldLabels: Record<string,string> = { date: "Datum", timeFrom: "Beginn", timeTo: "Ende", durationHours: "Stunden", durationMinutes: "Minuten", breakMinutes: "Pause (Min.)", comment: "Kommentar", categoryId: "Kategorie" };
export function Requests({ manager, userId }: { manager: boolean; userId: string }) {
  const requests = useQuery({ queryKey: ["requests"], queryFn: () => json<{ requests: RequestRow[] }>("/api/mod-requests") });
  const corrections = useQuery({ queryKey: ["corrections"], queryFn: () => json<{ corrections: Correction[] }>("/api/time/corrections") });
  const action = useAction();
  return <section id="antraege" className="space-y-4"><h2 className="text-[16px] font-semibold tracking-[-0.02em]">{manager ? "Anträge bearbeiten" : "Anträge und Schichttausch"}</h2><ErrorMessage error={requests.error || corrections.error} />
    <div className="grid gap-4 lg:grid-cols-2"><Card className="p-4"><h3 className="text-[14px] font-semibold tracking-[-0.02em]">Übernahmen und Schichttausch</h3>{requests.isPending ? <p>Lädt …</p> : !requests.data?.requests.length ? <p className="text-sm text-muted-foreground">Keine Anträge vorhanden.</p> : requests.data.requests.map(r => <div key={r.id} className="space-y-2 border-t py-3"><p className="font-medium">{r.kind === "SWAP" ? "Schichttausch" : "Übernahme"} · {labels[r.state]}</p><p className="tabular text-sm">{r.user ? `${r.user.firstName} ${r.user.lastName} · ` : ""}{dateLabel(r.shift.date)} · {r.shift.shiftFrom}–{r.shift.shiftTo} · {r.shift.title || "Schicht"}{r.shift.branch ? " · " + r.shift.branch.name : ""}</p>{r.note && <p className="text-sm">{r.note}</p>}
      {r.state === "OPEN" && <div className="flex flex-wrap gap-2">{r.can.decide ? <><Button size="sm" disabled={action.isPending || (r.kind === "SWAP" && !r.targetUserId)} onClick={() => action.mutate({ url: "/api/mod-requests/" + r.id, method: "PATCH", data: { state: "ACCEPTED" }, message: "Antrag genehmigt" })}>Genehmigen</Button><Button size="sm" variant="outline" disabled={action.isPending} onClick={() => action.mutate({ url: "/api/mod-requests/" + r.id, method: "PATCH", data: { state: "DECLINED" }, message: "Antrag abgelehnt" })}>Ablehnen</Button></> : r.can.volunteer ? <Button size="sm" disabled={action.isPending} onClick={() => action.mutate({ url: "/api/mod-requests/" + r.id, method: "PATCH", data: { volunteer: true }, message: "Übernahme angeboten" })}>Übernahme anbieten</Button> : r.targetUserId === userId ? <p className="text-sm">Deine Übernahme wartet auf Freigabe.</p> : null}{r.can.withdraw && <Button size="sm" variant="outline" disabled={action.isPending} onClick={() => action.mutate({ url: "/api/mod-requests/" + r.id, method: "DELETE", message: "Antrag zurückgezogen" })}>Zurückziehen</Button>}</div>}
      {r.kind === "SWAP" && !r.targetUserId && r.state === "OPEN" && <p className="text-sm text-muted-foreground">Wartet auf eine passende Übernahme.</p>}
    </div>)}</Card>
    <Card className="p-4"><h3 className="text-[14px] font-semibold tracking-[-0.02em]">Zeitkorrekturen</h3>{corrections.isPending ? <p>Lädt …</p> : !corrections.data?.corrections.length ? <p className="text-sm text-muted-foreground">Keine Zeitkorrekturen vorhanden.</p> : corrections.data.corrections.map(c => <div key={c.id} className="space-y-2 border-t py-3"><p className="font-medium">{c.record.user.firstName} {c.record.user.lastName} · {dateLabel(c.record.date)}{c.record.branch ? " · " + c.record.branch.name : ""}</p><p className="text-sm">{c.reason} · {labels[c.status]}</p><dl className="text-sm">{Object.entries(c.proposed).map(([key,value]) => <div key={key}><dt className="inline text-muted-foreground">{fieldLabels[key] || key}: </dt><dd className="inline">{String(c.before[key] ?? "–")} → {String(value ?? "–")}</dd></div>)}</dl>{c.canDecide && <div className="flex gap-2"><Button size="sm" disabled={action.isPending} onClick={() => action.mutate({ url: "/api/time/corrections", method: "PATCH", data: { id: c.id, status: "APPROVED" }, message: "Zeitkorrektur bestätigt" })}>Bestätigen</Button><Button size="sm" variant="outline" disabled={action.isPending} onClick={() => action.mutate({ url: "/api/time/corrections", method: "PATCH", data: { id: c.id, status: "DECLINED" }, message: "Zeitkorrektur abgelehnt" })}>Ablehnen</Button></div>}</div>)}</Card></div>
  </section>;
}
